// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHG9Bdo-20qnq8LnqxefaP5dY7y57SIV8',
    appId: '1:110026818267:web:eed3f7944f2a58b82882fe',
    messagingSenderId: '110026818267',
    projectId: 'employapp-bd61e',
    authDomain: 'employapp-bd61e.firebaseapp.com',
    storageBucket: 'employapp-bd61e.firebasestorage.app',
    measurementId: 'G-3YSLE3CLTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhCvApUOL_bfCSX3HICCCBLAlaNxnSR28',
    appId: '1:110026818267:android:2ca1c4aed389562d2882fe',
    messagingSenderId: '110026818267',
    projectId: 'employapp-bd61e',
    storageBucket: 'employapp-bd61e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvuEK7aHHtU067Ln5A3m3ES-thlRgWTec',
    appId: '1:110026818267:ios:18d6a72289118abf2882fe',
    messagingSenderId: '110026818267',
    projectId: 'employapp-bd61e',
    storageBucket: 'employapp-bd61e.firebasestorage.app',
    iosBundleId: 'com.example.employForm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvuEK7aHHtU067Ln5A3m3ES-thlRgWTec',
    appId: '1:110026818267:ios:18d6a72289118abf2882fe',
    messagingSenderId: '110026818267',
    projectId: 'employapp-bd61e',
    storageBucket: 'employapp-bd61e.firebasestorage.app',
    iosBundleId: 'com.example.employForm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHG9Bdo-20qnq8LnqxefaP5dY7y57SIV8',
    appId: '1:110026818267:web:f358120d08a3d0ba2882fe',
    messagingSenderId: '110026818267',
    projectId: 'employapp-bd61e',
    authDomain: 'employapp-bd61e.firebaseapp.com',
    storageBucket: 'employapp-bd61e.firebasestorage.app',
    measurementId: 'G-LDBG027T1K',
  );

}